
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tk_menorigual = 43;
  public static final int tk_while = 19;
  public static final int tk_sub = 27;
  public static final int tk_module = 30;
  public static final int tk_boolean = 9;
  public static final int tk_step = 20;
  public static final int tk_to = 17;
  public static final int tk_false = 25;
  public static final int tk_valorString = 59;
  public static final int tk_Resta = 32;
  public static final int tk_mayorigual = 41;
  public static final int tk_public = 29;
  public static final int tk_xor = 39;
  public static final int tk_Multiplicacion = 33;
  public static final int tk_writeline = 2;
  public static final int tk_as = 51;
  public static final int tk_Igual = 44;
  public static final int tk_for = 16;
  public static final int tk_function = 26;
  public static final int tk_do = 23;
  public static final int tk_not = 38;
  public static final int tk_and = 36;
  public static final int tk_structure = 28;
  public static final int tk_Suma = 31;
  public static final int EOF = 0;
  public static final int tk_write = 54;
  public static final int error = 1;
  public static final int tk_sys = 4;
  public static final int tk_Coma = 47;
  public static final int tk_dim = 50;
  public static final int tk_exit = 52;
  public static final int tk_next = 22;
  public static final int tk_loop = 18;
  public static final int tk_main = 57;
  public static final int ERROR = 7;
  public static final int tk_cs = 5;
  public static final int tk_mayorque = 40;
  public static final int tk_until = 21;
  public static final int tk_ParentesisC = 46;
  public static final int tk_mod = 35;
  public static final int tk_true = 24;
  public static final int tk_ParentesisA = 45;
  public static final int tk_like = 3;
  public static final int tk_null = 6;
  public static final int tk_or = 37;
  public static final int tk_elseif = 14;
  public static final int tk_byval = 11;
  public static final int tk_integer = 8;
  public static final int tk_String = 10;
  public static final int tk_Division = 34;
  public static final int tk_if = 12;
  public static final int tk_ampersant = 48;
  public static final int tk_else = 15;
  public static final int tk_read = 55;
  public static final int tk_end = 56;
  public static final int tk_Numero = 61;
  public static final int tk_Linea = 58;
  public static final int tk_return = 53;
  public static final int tk_then = 13;
  public static final int tk_punto = 49;
  public static final int tk_menorque = 42;
  public static final int tk_Identificador = 60;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tk_writeline",
  "tk_like",
  "tk_sys",
  "tk_cs",
  "tk_null",
  "ERROR",
  "tk_integer",
  "tk_boolean",
  "tk_String",
  "tk_byval",
  "tk_if",
  "tk_then",
  "tk_elseif",
  "tk_else",
  "tk_for",
  "tk_to",
  "tk_loop",
  "tk_while",
  "tk_step",
  "tk_until",
  "tk_next",
  "tk_do",
  "tk_true",
  "tk_false",
  "tk_function",
  "tk_sub",
  "tk_structure",
  "tk_public",
  "tk_module",
  "tk_Suma",
  "tk_Resta",
  "tk_Multiplicacion",
  "tk_Division",
  "tk_mod",
  "tk_and",
  "tk_or",
  "tk_not",
  "tk_xor",
  "tk_mayorque",
  "tk_mayorigual",
  "tk_menorque",
  "tk_menorigual",
  "tk_Igual",
  "tk_ParentesisA",
  "tk_ParentesisC",
  "tk_Coma",
  "tk_ampersant",
  "tk_punto",
  "tk_dim",
  "tk_as",
  "tk_exit",
  "tk_return",
  "tk_write",
  "tk_read",
  "tk_end",
  "tk_main",
  "tk_Linea",
  "tk_valorString",
  "tk_Identificador",
  "tk_Numero"
  };
}

