
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tk_menorigual = 36;
  public static final int tk_while = 16;
  public static final int tk_sub = 23;
  public static final int tk_module = 26;
  public static final int tk_boolean = 6;
  public static final int tk_step = 17;
  public static final int tk_to = 14;
  public static final int tk_false = 21;
  public static final int tk_valorString = 49;
  public static final int tk_Resta = 28;
  public static final int tk_mayorigual = 34;
  public static final int tk_public = 25;
  public static final int tk_Multiplicacion = 29;
  public static final int tk_writeline = 2;
  public static final int tk_comentario = 4;
  public static final int tk_as = 43;
  public static final int tk_Igual = 37;
  public static final int tk_for = 13;
  public static final int tk_function = 22;
  public static final int tk_do = 19;
  public static final int tk_structure = 24;
  public static final int tk_readline = 45;
  public static final int tk_Suma = 27;
  public static final int EOF = 0;
  public static final int tk_Potencia = 32;
  public static final int error = 1;
  public static final int tk_Coma = 40;
  public static final int tk_dim = 42;
  public static final int tk_exit = 44;
  public static final int tk_next = 18;
  public static final int tk_loop = 15;
  public static final int tk_main = 47;
  public static final int tk_cs = 3;
  public static final int tk_mayorque = 33;
  public static final int tk_ParentesisC = 39;
  public static final int tk_true = 20;
  public static final int tk_ParentesisA = 38;
  public static final int tk_elseif = 11;
  public static final int tk_byval = 8;
  public static final int tk_integer = 5;
  public static final int tk_String = 7;
  public static final int tk_Division = 30;
  public static final int tk_if = 9;
  public static final int tk_Signomod = 31;
  public static final int tk_else = 12;
  public static final int tk_end = 46;
  public static final int tk_Numero = 51;
  public static final int tk_Linea = 48;
  public static final int tk_then = 10;
  public static final int tk_punto = 41;
  public static final int tk_menorque = 35;
  public static final int tk_Identificador = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tk_writeline",
  "tk_cs",
  "tk_comentario",
  "tk_integer",
  "tk_boolean",
  "tk_String",
  "tk_byval",
  "tk_if",
  "tk_then",
  "tk_elseif",
  "tk_else",
  "tk_for",
  "tk_to",
  "tk_loop",
  "tk_while",
  "tk_step",
  "tk_next",
  "tk_do",
  "tk_true",
  "tk_false",
  "tk_function",
  "tk_sub",
  "tk_structure",
  "tk_public",
  "tk_module",
  "tk_Suma",
  "tk_Resta",
  "tk_Multiplicacion",
  "tk_Division",
  "tk_Signomod",
  "tk_Potencia",
  "tk_mayorque",
  "tk_mayorigual",
  "tk_menorque",
  "tk_menorigual",
  "tk_Igual",
  "tk_ParentesisA",
  "tk_ParentesisC",
  "tk_Coma",
  "tk_punto",
  "tk_dim",
  "tk_as",
  "tk_exit",
  "tk_readline",
  "tk_end",
  "tk_main",
  "tk_Linea",
  "tk_valorString",
  "tk_Identificador",
  "tk_Numero"
  };
}

